### ISSUE TITLE
Not working in Nextcloud docker (Could not fetch secrets)

### ISSUE THREAD

**Issue by sorcer1122** [theCalcaholic/nextcloud-secrets#15] opened 2023-01-10 15:38 UTC
Hi,

Installed Secrets in the latest Nextcloud (25.0.2) and it is not working for me, getting 'could not fetch secrets'. If I click on New Secret a few times, I can generate it. Once I open the link I get the following:

![image](https://user-images.githubusercontent.com/15838362/211595090-7600bc61-5aba-4fc7-b6ba-42314b39a0e0.png)

Here is the log extract:

![image](https://user-images.githubusercontent.com/15838362/211594828-49225506-9165-4eff-bce4-084940813498.png)

Any ideas where to dig?

**Comment by theCalcaholic** [comment] 2023-01-11 10:40
Hi, thanks for the report. Looks like there is an issue with my serialization method.

I'm working on a fix

**Comment by sorcer1122** [comment] 2023-01-11 10:53
Oh, that was a quick response, thanks!

Would love to test it, if possible.

**Comment by theCalcaholic** [comment] 2023-01-23 06:00
This was a lot harder to solve than I anticipated, but I have now prepared a fix. Can you please try the version from [this release](https://github.com/theCalcaholic/nextcloud-secrets/releases/tag/test-fix-serialization-rc1) (download the secrets.tar.gz, remove the old `secrets` directory from your NC apps directory and replace it from the extracted archive)?

**Comment by sorcer1122** [comment] 2023-01-23 20:25
Just tried it, was not able even to enable the app. Here is the log:

```
[index] Error: Exception: OCA\Secrets\Migration\Version1001Date20230122142756::fixSerialization(): Argument #1 ($utf8Str) must be of type ?string, resource given, called in /var/www/html/apps/secrets/lib/Migration/Version1001Date20230122142756.php on line 97 in file '/var/www/html/apps/secrets/lib/Migration/Version1001Date20230122142756.php' line 102 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
1. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, ["settings.AppSettings.enableApps"])
2. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/settings/apps/enable")
3. /var/www/html/index.php line 36
   OC::handleRequest()

```

**Comment by theCalcaholic** [comment] 2023-01-23 21:40
Now that's *really* strange. No idea how that could happen. Would you mind giving me a dump of the (encrypted) secrets table from your database?

If you could execute the following SQL statement against your db and send me the output, that could clear things up:

```sql
SELECT * FROM oc_secrets;
```

If you're using mysql, the command you need would look like this, for example:

```sh
mysql -u <nc-user> -D <db-name> -p -e 'SELECT * from oc_secrets;'
```

You could upload the output of the command here: https://cloud.knoeppler.org/index.php/s/NDDWqH97gz4g6tR

**Comment by theCalcaholic** [comment] 2023-01-25 13:36
@sorcer1122 I have tried to come up with a fix even though I couldn't reproduce the issue.

Can you try this (hopefully fixed) version of the app and tell me if it worked for you?
https://cloud.knoeppler.org/index.php/s/wfGMnBTXC66Xbqz

How to install:

1. Navigate to your `nextcloud/apps` folder
2. Download the *.tar.gz file to your server: `wget https://cloud.knoeppler.org/index.php/s/wfGMnBTXC66Xbqz/download/secrets-fix-resource-handling.tar.gz -O ./secrets.tar.gz`
3. Remove the existing "secrets" directory: `rm -r ./secrets`
4. Extract the archive: `tar xf secrets.tar.gz`
5. Fix ownership of the secrets folder: `sudo chown -R www-data: ./secrets` (assuming the user of your php process/web service is `www-data` - otherwise, replace with that user)
6. Remove the archive: `rm secrets.tar.gz`

**Comment by theCalcaholic** [comment] 2023-01-25 18:55
Another user has tracked down the issue to a compatibility problem with postgresql. It is hopefully fixed in version [1.3.0](https://github.com/theCalcaholic/nextcloud-secrets/releases/tag/v1.3.0). Let me know if the fix works :)

**Closed by theCalcaholic** 2023-01-25 18:55 UTC
Labels: bug

**Comment by LenKer-OnE** [comment] 2023-01-26 16:19
I tried both, 1.3.0 from releases here and 1.3.1 from store.

Output is the same:

[index] Fehler: Exception: utf8_decode(): Argument #1 ($string) must be of type string, resource given in file '/var/www/html/custom_apps/secrets/lib/Migration/Version1001Date20230122142756.php' line 101 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "enableApps")
1. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "enableApps", OC\AppFramework\ ... {}, ["settings.AppSettings.enableApps"])
2. /var/www/html/lib/base.php line 1047
   OC\Route\Router->match("/settings/apps/enable")
3. /var/www/html/index.php line 36
   OC::handleRequest()

POST /settings/apps/enable

**Comment by theCalcaholic** [comment] 2023-01-26 16:48
Okay, in that case, your best course of action would be to delete the existing secrets from the database and reinstall the app.
You can do so (assuming you're using postgresql) with the following command:

```
psql -U <dbuser-from-config.php> -d nextcloud -c 'DELETE FROM oc_secrets;'
```

**Comment by LenKer-OnE** [comment] 2023-01-26 21:35
Okay, it's working now. Thanks for fast support!

For those who are using Nextcloud AIO docker image:
1. `sudo docker exec -it nextcloud-aio-database bash` 
2. `psql -U oc_nextcloud -d nextcloud_database -c "DROP TABLE oc_secrets; DELETE FROM oc_migrations WHERE app='secrets';"`
