### ISSUE TITLE
Secrets app does nothing

### ISSUE THREAD

**Issue by tuxick** [theCalcaholic/nextcloud-secrets#48] opened 2024-06-28 09:48 UTC
Installed Secrets app on up to data Hub 8, i see an icon for it, but when i click on that all i see is current page reloading. Nothing in log either.
This is on Ubuntu 22.04, php 8.1 source install. 

Same app is working fine on 2 other systems, one in ubuntu 20.04 snap and another on ubuntu 20.04 source install with php 7.4.

**Comment by theCalcaholic** [comment] 2024-07-09 20:04
That's weird... If you hit F12 and go to the console tab in the developer tools of your browser - are there any errors?

**Comment by tkawchak** [comment] 2024-07-23 23:45
Same thing for me. When I hover over the secrets app icon, the preview link is always just redirecting to the same page that nextcloud is currently on, as opposed to `/apps/secrets`. If I go directly to `/apps/secrets`, the secrets app loads fine for me.

**Comment by vidlb** [comment] 2024-07-26 08:06
Same for me, this is like this since update to NC 29.  
This is a soft bug without an error message, but there is an INFO message linked to the issue : 
`RouteNotFoundException Unable to generate a URL for the named route "secrets.page.index" as such route does not exist.`
Not sure if this is a Secrets issue or a NC issue :  the polls app was also broken last month but is fixed now.  
And yes it's working if you type the URL directly, thanks for the trick @tkawchak

**Comment by theCalcaholic** [comment] 2024-07-27 09:11
Interesting, thank you for the additional context. I didn't encounter this issue when testing with NC 29, so maybe it's a caching issue that only happens when updating NC from earlier versions.

I'll see if I can reproduce it now.

**Comment by ThibautPlg** [comment] 2024-08-09 07:20
Hi,
I've faced the same issue. Turns out the problem comes from the fulltextsearch app. Enable/Disable it and it should fix the problem.
See https://github.com/nextcloud/fulltextsearch/issues/842

Best regards,

**Comment by theCalcaholic** [comment] 2024-08-09 23:25
I see, I'll close this as 3rd party issue then.

**Closed by theCalcaholic** 2024-08-09 23:25 UTC

**Comment by tuxick** [comment] 2024-12-27 12:55
I upgraded as in extracting latest tarball and copy config.php, and it's working now. Sadly no clue about why it was failing before.
